version: '3.8'

volumes:
  data:

services:
  php:
    build: ./build/php
    restart: always
    ports:
      - 80:80
    volumes:
      - ./src/php:/var/www
    environment:
      # Set XDEBUG_MODE to "off" for Production-ready application
      XDEBUG_MODE: develop,debug

  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
    env_file:
      ./build/db/db.env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080